# Generated by Django 4.2.2 on 2023-07-01 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('educational', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('food_id', models.IntegerField(primary_key=True, serialize=False)),
                ('food_name', models.CharField(max_length=45, unique=True)),
                ('meal', models.CharField(max_length=45)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Research',
            fields=[
                ('research_id', models.IntegerField(primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=45, null=True)),
                ('title', models.CharField(max_length=45, null=True)),
                ('book_flag', models.BooleanField(null=True)),
                ('paper_flag', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('sport_id', models.IntegerField(primary_key=True, serialize=False)),
                ('SportPrice', models.IntegerField()),
                ('SportCapacity', models.CharField(max_length=45)),
                ('SportName', models.CharField(max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeisureClass',
            fields=[
                ('l_from', models.DateField(null=True)),
                ('l_to', models.DateField(null=True)),
                ('l_time', models.TimeField(null=True)),
                ('day1', models.CharField(max_length=45, null=True)),
                ('day2', models.CharField(max_length=45, null=True)),
                ('leisure_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='service.sport')),
            ],
        ),
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('address', models.CharField(max_length=100, null=True)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='service.sport')),
            ],
        ),
        migrations.CreateModel(
            name='ResearchReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_from', models.DateField(null=True)),
                ('r_to', models.DateField(null=True)),
                ('research', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.research')),
                ('studentNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educational.student')),
            ],
        ),
        migrations.AddField(
            model_name='research',
            name='students',
            field=models.ManyToManyField(through='service.ResearchReservation', to='educational.student'),
        ),
        migrations.CreateModel(
            name='FoodReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_reservation_date', models.DateField()),
                ('food_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.food')),
                ('studentNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educational.student')),
            ],
        ),
        migrations.AddField(
            model_name='food',
            name='students',
            field=models.ManyToManyField(through='service.FoodReservation', to='educational.student'),
        ),
        migrations.CreateModel(
            name='RegisterLeisureClass',
            fields=[
                ('registerLeisureClass_id', models.IntegerField(primary_key=True, serialize=False)),
                ('studentNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educational.student')),
                ('leisure_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.leisureclass')),
            ],
        ),
        migrations.CreateModel(
            name='PoolReservation',
            fields=[
                ('poolReservation_id', models.IntegerField(primary_key=True, serialize=False)),
                ('from_field', models.TimeField(null=True)),
                ('to_field', models.TimeField(null=True)),
                ('date_pool', models.DateField(null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educational.student')),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.pool')),
            ],
        ),
        migrations.AddField(
            model_name='pool',
            name='students',
            field=models.ManyToManyField(through='service.PoolReservation', to='educational.student'),
        ),
        migrations.AddField(
            model_name='leisureclass',
            name='students',
            field=models.ManyToManyField(through='service.RegisterLeisureClass', to='educational.student'),
        ),
    ]
