# Generated by Django 4.2.2 on 2023-07-01 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_code', models.IntegerField(primary_key=True, serialize=False)),
                ('course_group', models.IntegerField()),
                ('course_subject', models.CharField(max_length=45)),
                ('credit', models.IntegerField()),
                ('classNo', models.CharField(max_length=45)),
                ('examDate', models.DateField()),
                ('examTime', models.TimeField()),
                ('chart_presented_term', models.IntegerField()),
                ('is_digital_signature', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('departmentNo', models.IntegerField(primary_key=True, serialize=False)),
                ('field', models.CharField(max_length=45, null=True)),
                ('faculty', models.CharField(max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('personnelCode', models.IntegerField(primary_key=True, serialize=False)),
                ('nationalCode', models.CharField(max_length=10, unique=True)),
                ('firstName', models.CharField(max_length=45)),
                ('lastName', models.CharField(max_length=45)),
                ('phoneNumber', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=45)),
                ('address', models.CharField(max_length=100, null=True)),
                ('lastEducationCertificate', models.CharField(max_length=45)),
                ('gender', models.CharField(max_length=6)),
                ('degree', models.CharField(max_length=45)),
                ('supervisor_flag', models.BooleanField()),
                ('department_manager_flag', models.BooleanField()),
                ('departmentNo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='educational.department')),
            ],
        ),
        migrations.CreateModel(
            name='RollCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isPresent', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('studentNo', models.IntegerField(primary_key=True, serialize=False)),
                ('nationalCode', models.CharField(max_length=10, unique=True)),
                ('firstName', models.CharField(max_length=45)),
                ('lastName', models.CharField(max_length=45)),
                ('phoneNumber', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=45)),
                ('address', models.CharField(max_length=100, null=True)),
                ('entranceYear', models.IntegerField()),
                ('gender', models.CharField(max_length=6)),
                ('birthdate', models.DateField(null=True)),
                ('nationality', models.CharField(max_length=45, null=True)),
                ('gpa', models.FloatField(null=True)),
                ('passed_credit', models.IntegerField(null=True)),
                ('balance', models.IntegerField(null=True)),
                ('taken_credit', models.IntegerField(null=True)),
                ('deptNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educational.department')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educational.professor')),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('term_id', models.IntegerField(primary_key=True, serialize=False)),
                ('year', models.IntegerField(null=True)),
                ('semesterNo', models.IntegerField(null=True)),
                ('selection_unit_start_date', models.DateField(null=True)),
                ('selection_unit_end_date', models.DateField(null=True)),
                ('delete_lesson_end_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TakeCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_grade', models.FloatField(null=True)),
                ('professor_grade', models.IntegerField(null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educational.course')),
                ('studentNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educational.student', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('session_id', models.IntegerField(primary_key=True, serialize=False)),
                ('session_No', models.IntegerField()),
                ('session_date', models.DateField(null=True)),
                ('topic', models.CharField(max_length=45, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educational.course')),
                ('students', models.ManyToManyField(through='educational.RollCall', to='educational.student')),
            ],
        ),
        migrations.AddField(
            model_name='rollcall',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educational.session'),
        ),
        migrations.AddField(
            model_name='rollcall',
            name='studentNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educational.student'),
        ),
        migrations.CreateModel(
            name='CourseSchedule',
            fields=[
                ('cs_id', models.IntegerField(primary_key=True, serialize=False)),
                ('course_time', models.TimeField(null=True)),
                ('course_day', models.CharField(max_length=45, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educational.course')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='deptNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educational.department'),
        ),
        migrations.AddField(
            model_name='course',
            name='profNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educational.professor'),
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(through='educational.TakeCourses', to='educational.student'),
        ),
        migrations.AddField(
            model_name='course',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educational.term'),
        ),
    ]
