# Generated by Django 4.2.2 on 2023-07-01 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='takecourses',
            name='studentNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educational.student'),
        ),
    ]
